spring:
  cloud:
    stream:
      bindings:
        adListener-in-0:
          destination: active-inventories
        adListener-in-1:
          destination: ad-clicks
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              commit.interval.ms: 10000
              state.dir: state-store
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
