spring:
  cloud:
    stream:
      function:
        definition: hadoop;notification
      bindings:
        notification-in-0:
          destination: avro-pos-topic
        notification-out-0:
          destination: loyalty-topic
        hadoop-in-0:
          destination: avro-pos-topic
        hadoop-out-0:
          destination: hadoop-sink-topic
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
          bindings:
            notification-in-0:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            notification-out-0:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            hadoop-in-0:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            hadoop-out-0:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde